### ISSUE TITLE
Upgrade from 0.9.1 to 0.9.3 requires devices to re-register with Azure Notification Hubs 

### ISSUE THREAD

**Issue by jbenzshawel** [CatalystCode/react-native-azurenotificationhub#100]
## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- Platforms: Android

- Android version: Android 8 and Android 10

## Issues and Steps to Reproduce
1. Register device with push notifications and version `0.9.1`
2. Send push notifications to device with registered tag
3. Update package to `0.9.3` and make necessary changes to `AndroidManifest.xml` and `build.gradle`
4. Run `./gradlew clean` 
5. Send push notification to tag registered with version `0.9.1`
6. Application crashes 

Note after re-registering with tags push notifications work as normal

## Expected Behavior
App should be able to use existing tag registrations with new package 

## Actual Behavior
App crashes when push notification received until tags are re-registered 

## Android Logs
I think the error corresponding to this is this part however all logs are attached:

```
--------- beginning of crash
02-22 09:29:58.324 11850 11850 E AndroidRuntime: FATAL EXCEPTION: main
02-22 09:29:58.324 11850 11850 E AndroidRuntime: Process: com.XXXXXXX.mobiledev, PID: 11850
02-22 09:29:58.324 11850 11850 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.microsoft.windowsazure.notifications.NotificationsBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.windowsazure.notifications.NotificationsBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/base.apk"],nativeLibraryDirectories=[/data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/lib/x86, /data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3774)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.windowsazure.notifications.NotificationsBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/base.apk"],nativeLibraryDirectories=[/data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/lib/x86, /data/app/com.XXXXXXX.mobiledev-MtI2itLaNYncL2q8iAi2_A==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3767)
02-22 09:29:58.324 11850 11850 E AndroidRuntime: 	... 8 more
02-22 09:29:58.401  2099 12034 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-22 09:29:58.415  2099  3087 W ActivityTaskManager:   Force finishing activity com.XXXXXXX.mobiledev/.MainActivity
02-22 09:29:58.417  2099  3087 W InputReader: Device has associated, but no associated display id.
02-22 09:29:58.445  2099  2138 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-22 09:29:58.449  2099  2138 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-22 09:29:58.418  2099  3087 I chatty  : uid=1000(system) Binder:2099_A identical 8 lines
02-22 09:29:58.418  2099  3087 W InputReader: Device has associated, but no associated display id.
02-22 09:29:58.449  2293  2293 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.XXXXXXX.mobiledev (has extras) }
02-22 09:29:58.452 11850 11850 I Process : Sending signal. PID: 11850 SIG: 9
02-22 09:29:58.511  2099  2229 W InputDispatcher: channel 'fafb745 com.XXXXXXX.mobiledev/com.XXXXXXX.mobiledev.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-22 09:29:58.511  2099  2229 E InputDispatcher: channel 'fafb745 com.XXXXXXX.mobiledev/com.XXXXXXX.mobiledev.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
[logCat.txt](https://github.com/CatalystCode/react-native-azurenotificationhub/files/4239765/logCat.txt)

Looking at the error I think this might be related to the configuration change around [removing the following](https://github.com/CatalystCode/react-native-azurenotificationhub/pull/94/files#diff-6d84edcdf2726a601a321395bf7a0f54L28) in the Android Manifest without re-registering with Azure Notification Hubs:

```xml
      <receiver	
        android:name="com.microsoft.windowsazure.notifications.NotificationsBroadcastReceiver"	
        android:permission="com.google.android.c2dm.permission.SEND">	
        <intent-filter>	
          <action android:name="com.google.android.c2dm.intent.RECEIVE" />	
        </intent-filter>	
      </receiver>
```

**Comment by phongcao** [comment]
@jbenzshawel Do you think that this issue is a blocker that prevents your app from using v0.9.3?

**Comment by jbenzshawel** [comment]
Due to having push notifications stabilized with v0.9.1 we opted to stay at v0.9.1 for the time being. Having the app crash after receiving the first new push notification with v0.9.3 is not a risk we want to take at the moment.

**Comment by phongcao** [comment]
That makes total sense. I'll see what we can do with this issue.

**Comment by phongcao** [comment]
@jbenzshawel I spent some time today trying to reproduce this issue but didn't succeed. Between step 4 & 5, I assume that you must have rebuilt the apk file and re-install it on your device correct?

```
4. Run "./gradlew clean"
   Run "./gradlew assembleDebug"
   CD into "build\outputs\apk\debug" and run "adb install app-debug.apk"
5. Send push notification to tag registered with version 0.9.1

**Comment by jbenzshawel** [comment]
Interesting. Here are some more detailed steps:

1. Install Android version `0.9.1` and follow README Android configuration steps for this version: https://github.com/CatalystCode/react-native-azurenotificationhub/tree/ca88e24d02cea630ffd90f3cb96e506146d41d24#android-installation
2. Build app and run the app using the react-native CLI on an Android device or emulator:
```
react-native run-android
````
3. Register application for push notifications, tags, and received event listeners: 
```js
PushNotificationEmitter.addListener(DEVICE_NOTIF_EVENT, this._onRemoteNotification);

NotificationHub.register({connectionString, hubName, senderID, tags})
      .catch(reason => console.warn(reason));
```
4. Send push notification to tag registered and verify notifications are received on the device/emulator
5. Change package.json `react-native-azurenotificationhub` from `0.9.1` to `0.9.3` and run `yarn install`
6. Update the configuration according to the updated Android config for `0.9.3` changing the `Android.Manifest.xml`, `/android/build.gradle`, and `/android/app/build.gradle` files
7. Run `./gradlew clean`
8. Run the app on an emulator or device that had the previous version that was using version `0.9.1` installed
```
react-native run-android
```
9. Push a notification to a previously registered tag
10. App crashes when `onRemoteNotification` event fires

**Comment by theromie** [comment]
I have installed 0.9.4 version and when i am sending Test message from Portal App crashes when `onRemoteNotification` event fires

**Comment by Luftzig** [comment]
I also encounter this bug with 0.9.5-patched.1, but I'm not sure if I've done the `Android.Manifest.xml` steps because I couldn't find the instructions. Before upgrading we used our own fork that was at least over a year behind so I'm not sure to what version it corresponded.
