### ISSUE TITLE
onNewToken android error

### ISSUE THREAD

**Issue by yasaricli** [CatalystCode/react-native-azurenotificationhub#110]
We got this error in our production app today.

Versions:

**react-native-azurenotificationhub: ^0.9.0**
**react-native: 0.59.10 => 0.59.10**

Crashlytics:

```
ReactNativeFirebaseMessagingService.java line 17
com.azure.reactnative.notificationhub.ReactNativeFirebaseMessagingService.onNewToken
```

Error Detail:

```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx/com.azure.reactnative.notificationhub.ReactNativeRegistrationIntentService }: app is in background uid UidRecord{ec9eef1 u0a216 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.azure.reactnative.notificationhub.ReactNativeFirebaseMessagingService.onNewToken(ReactNativeFirebaseMessagingService.java:17)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.1:95)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.1:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)
```

Thanks.

**Comment by phongcao** [comment]
This issue seems related to [Background Execution Limits](https://developer.android.com/about/versions/oreo/background.html#services) on Android 8 as mentioned in this thread:

https://stackoverflow.com/questions/46117554/firebasemessagingservice-crashes-on-android-o-due-to-background-execution-limits

I'll have a look at it soon.

**Comment by essesve** [comment]
Hello;

We get the same error:

```
 Fatal Exception: java.lang.IllegalStateException:
Not allowed to start service Intent  app is in background uid UidRecord
```

++

**Comment by phongcao** [comment]
@yasaricli @essesve Fixed in the master branch. Please remember to update your manifest file:

`android:permission="android.permission.BIND_JOB_SERVICE"`

**Comment by yasaricli** [comment]
It worked but I am experiencing the following error #116

**Comment by yasaricli** [comment]
Thanks @phongcao 

The package has been updated as a master since you are currently unable to release.

    yarn add https://github.com/CatalystCode/react-native-azurenotificationhub.git

no problem for android.

If any error occurs again, I can report it here.

Thanks again.

**Comment by phongcao** [comment]
@yasaricli You're welcome. I'm going to release a new version soon.

**Comment by phongcao** [comment]
v0.9.4 has been published!
