### ISSUE TITLE
Only receiving notifications on emulators instead of real devices

### ISSUE THREAD

**Issue by ramonvermeulen** [CatalystCode/react-native-azurenotificationhub#140]
## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- Platforms: Android

- Android version: 9

- iOS version: -

## Issues and Steps to Reproduce
I can only receive notifications on emulators instead of real devices. Once I install my application on a real device as debug or release build, the notifications won't show up. On the emulator they actually do show up. I followed the Android installation guide.

Actually one thing showed up in logcat which was kind of weird:

```
2020-04-07 16:08:42.030 26233-26327/nl.rocmn.mijn W/nl.rocmn.mijn: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
2020-04-07 16:08:42.302 26233-26233/nl.rocmn.mijn D/ViewRootImpl@f4031cd[MainActivity]: Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x1 surface={valid=true 488232644608} changed=false
2020-04-07 16:08:42.348 26233-26323/nl.rocmn.mijn I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-04-07 16:08:42.349 26233-26323/nl.rocmn.mijn I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-04-07 16:08:42.396 26233-26334/nl.rocmn.mijn D/SoLoader: About to load: libimagepipeline.so
2020-04-07 16:08:42.396 26233-26334/nl.rocmn.mijn D/SoLoader: libimagepipeline.so not found on /data/data/nl.rocmn.mijn/lib-main
2020-04-07 16:08:42.397 26233-26334/nl.rocmn.mijn D/SoLoader: libimagepipeline.so found on /data/app/nl.rocmn.mijn-Nps5x-FK1oQMmLswidAOJQ==/lib/arm64
2020-04-07 16:08:42.397 26233-26334/nl.rocmn.mijn D/SoLoader: Not resolving dependencies for libimagepipeline.so
2020-04-07 16:08:42.398 26233-26334/nl.rocmn.mijn D/SoLoader: Loaded: libimagepipeline.so
2020-04-07 16:08:42.635 26233-26323/nl.rocmn.mijn E/ReactNativeRegistration: Failed to complete token refresh
    com.microsoft.windowsazure.messaging.NotificationHubResourceNotFoundException: Resource not found
        at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:248)
        at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:172)
        at com.microsoft.windowsazure.messaging.NotificationHub.createRegistrationId(NotificationHub.java:463)
        at com.microsoft.windowsazure.messaging.NotificationHub.registerInternal(NotificationHub.java:396)
        at com.microsoft.windowsazure.messaging.NotificationHub.register(NotificationHub.java:144)
        at com.azure.reactnative.notificationhub.ReactNativeRegistrationIntentService$1.onSuccess(ReactNativeRegistrationIntentService.java:73)
        at com.azure.reactnative.notificationhub.ReactNativeRegistrationIntentService$1.onSuccess(ReactNativeRegistrationIntentService.java:53)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

But this error showed up in the logcat of the emulator as well, and in the emulator everything works fine. Besides that for some reason the Tags I register are not showing up in the azure portal.

## Expected Behavior
That I will receive notifications on real devices as well.

## Actual Behavior
On real devices notifications are not working.

## Link to Code
```
import React, { ComponentProps, ReactNode, useCallback, useEffect } from 'react';
import { NativeEventEmitter, TouchableOpacity } from 'react-native';

import * as RootNavigation from '../RootNavigation';
import config from '../config';
import { Routes } from '../constants';
import { ModificationType, ROCNotification, Type } from '../models/Notification';

const NotificationHub = require('react-native-azurenotificationhub');
const PushNotificationEmitter = new NativeEventEmitter(NotificationHub);

const EVENT_AZURE_NOTIFICATION_HUB_REGISTERED           = 'azureNotificationHubRegistered';
const EVENT_AZURE_NOTIFICATION_HUB_REGISTERED_ERROR     = 'azureNotificationHubRegisteredError';
const EVENT_REMOTE_NOTIFICATION_RECEIVED                = 'remoteNotificationReceived';

type Props = {
  children: ReactNode;
} & ComponentProps<typeof TouchableOpacity>;

export function AzureNotificationHub ({
  children
}: Props) {
  const connectionString = config.NOTIFICATION_CONNECTION_STRING;
  const senderID = config.NOTIFICATION_SENDER_ID;
  const hubName = config.NOTIFICATION_HUB_NAME;
  const tags = ['ROC-TEST'];

  const register = useCallback(async () => {
    try {
      console.log('register');
      const res = await NotificationHub.register({
        hubName,
        connectionString,
        senderID,
        tags
      });
      console.log('res: ', res); // actually logs {"uuid": "09a83bbc-2630-4a44-aef2-90e55fd3c16f"}
    } catch (err) {
      console.log(err);
    }
  }, [hubName, connectionString, senderID, tags]);

  const unRegister = useCallback(async () => {
    await NotificationHub.unregister();
  }, []);

  const _onRemoteNotification = useCallback((notification: ROCNotification) => {
    console.log(notification);
  }, []);

  useEffect(() => {
    register();
    PushNotificationEmitter.addListener(EVENT_REMOTE_NOTIFICATION_RECEIVED, _onRemoteNotification);
    return () => {
      unRegister();
      PushNotificationEmitter.removeAllListeners();
    }
  }, []);

  return (<>{children}</>);
}
```

My AndroidManifest.xml

```
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="nl.rocmn.mijn"
>
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notification"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <application
      android:usesCleartextTraffic="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <uses-library
              android:name="org.apache.http.legacy"
              android:required="false" />

      <service
              android:name="com.azure.reactnative.notificationhub.ReactNativeRegistrationIntentService"
              android:exported="false"
              android:permission="android.permission.BIND_JOB_SERVICE" />

      <service
              android:name="com.azure.reactnative.notificationhub.ReactNativeFirebaseMessagingService"
              android:stopWithTask="false">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTop"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data
                  android:pathPrefix="/android/callback"
                  android:host="nl.rocmn.mijn"
                  android:scheme="nl.rocmn.mijn" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
</manifest>
```

**Comment by ramonvermeulen** [comment]
Update: Finally found the bug! Due to this post I found somewhere in a deep hole on google (https://disqus.com/by/maravirginianavas/).
Apparently I used the wrong hub name, the weird thing is that the javascript runtime does not give any kind of error when using a wrong hubname, this made debugging of this issue really hard.

**Comment by phongcao** [comment]
Thanks for your update. It’s strange that this error doesn’t get caught.
